package projectGUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHUN
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

public class BookingInputForm extends javax.swing.JFrame {
    Connection myConn;
    Statement myStmt;
    ResultSet myRs;
    PreparedStatement pstmt;
    /**
     * Creates new form BookingInputForm
     */
    public BookingInputForm() {
        initComponents();
        setConnect();
    }
        public void setConnect(){
        
        try{
          myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_oop", "root", "");   //databaseName
        //  JOptionPane.showMessageDialog(null, "Connection success!!");          
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayBtn = new javax.swing.JButton();
        bookingPanel = new javax.swing.JPanel();
        memberIdLbl = new javax.swing.JLabel();
        numOfCourtLbl = new javax.swing.JLabel();
        bookingIdLbl = new javax.swing.JLabel();
        memberIdTxtfld = new javax.swing.JTextField();
        bookingIdTxtfld = new javax.swing.JTextField();
        numOfCourtTxtfld = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        requestActivityLbl = new javax.swing.JLabel();
        listActivityLbl1 = new javax.swing.JLabel();
        listActivityLbl2 = new javax.swing.JLabel();
        activityLbl = new javax.swing.JLabel();
        activityTxtfld = new javax.swing.JTextField();
        requestScheduleLbl = new javax.swing.JLabel();
        listScheduleLbl = new javax.swing.JLabel();
        scheduleLbl = new javax.swing.JLabel();
        scheduleTxtfld = new javax.swing.JTextField();
        inputBookingInformationLbl = new javax.swing.JLabel();
        profileUpdateBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(204, 0, 204));
        displayBtn.setText("DISPLAY/MANAGE DATA");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        bookingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        memberIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        memberIdLbl.setText("Member ID:");

        numOfCourtLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numOfCourtLbl.setText("Num Of Court:");

        bookingIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookingIdLbl.setText("Booking ID:");

        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(204, 0, 204));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        requestActivityLbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        requestActivityLbl.setForeground(new java.awt.Color(255, 51, 51));
        requestActivityLbl.setText("Please choose one of the activities!!!");

        listActivityLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listActivityLbl1.setForeground(new java.awt.Color(0, 51, 255));
        listActivityLbl1.setText("BADMINTION     PING PONG     TENNIS     BASKETBALL     ");

        listActivityLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listActivityLbl2.setForeground(new java.awt.Color(0, 51, 255));
        listActivityLbl2.setText("NETBALL     SQUASH     VOLLEYBALL     FUTSAL");

        activityLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        activityLbl.setText("Activity: ");

        requestScheduleLbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        requestScheduleLbl.setForeground(new java.awt.Color(255, 51, 51));
        requestScheduleLbl.setText("Please choose one of the schedules!!!");

        listScheduleLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listScheduleLbl.setForeground(new java.awt.Color(0, 51, 255));
        listScheduleLbl.setText("1200-1400     1400-1600     1600-1800");

        scheduleLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleLbl.setText("Schedule:");

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(requestActivityLbl))
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(requestScheduleLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberIdLbl)
                            .addComponent(bookingIdLbl)
                            .addComponent(numOfCourtLbl))
                        .addGap(51, 51, 51)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listActivityLbl1)
                            .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numOfCourtTxtfld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                .addComponent(bookingIdTxtfld, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(memberIdTxtfld, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingPanelLayout.createSequentialGroup()
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bookingPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(listActivityLbl2)
                                .addGap(70, 70, 70))
                            .addGroup(bookingPanelLayout.createSequentialGroup()
                                .addComponent(activityLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(scheduleTxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                    .addComponent(activityTxtfld))
                                .addGap(31, 31, 31)))
                        .addComponent(submitBtn)
                        .addGap(43, 43, 43))))
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(listScheduleLbl))
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scheduleLbl)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdLbl)
                    .addComponent(memberIdTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIdLbl)
                    .addComponent(bookingIdTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfCourtLbl)
                    .addComponent(numOfCourtTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(requestActivityLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listActivityLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addComponent(listActivityLbl2)
                        .addGap(18, 18, 18)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activityLbl)
                            .addComponent(activityTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingPanelLayout.createSequentialGroup()
                        .addComponent(submitBtn)
                        .addGap(35, 35, 35)))
                .addComponent(requestScheduleLbl)
                .addGap(18, 18, 18)
                .addComponent(listScheduleLbl)
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scheduleLbl)
                    .addComponent(scheduleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        inputBookingInformationLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        inputBookingInformationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputBookingInformationLbl.setText("Input Booking Information");

        profileUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profileUpdateBtn.setText("UPDATE PROFILE");
        profileUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileUpdateBtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("PROCEED PAYMENT >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputBookingInformationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profileUpdateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(displayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inputBookingInformationLbl)
                .addGap(18, 18, 18)
                .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileUpdateBtn)
                    .addComponent(displayBtn)
                    .addComponent(jButton2))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        BookingOutputForm outputform = new BookingOutputForm();
       outputform.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_displayBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String SQL = "INSERT INTO booking VALUES (?,?,?,?,?,?)";        //tableName
        try{
            Double price = 4.00;
            pstmt = myConn.prepareStatement(SQL);
            pstmt.setString(1, memberIdTxtfld.getText());
            pstmt.setString(2, bookingIdTxtfld.getText());
            pstmt.setInt(3, Integer.parseInt(numOfCourtTxtfld.getText()));
            pstmt.setDouble(4, price);
            pstmt.setString(5, activityTxtfld.getText());
            pstmt.setString(6, scheduleTxtfld.getText());
            pstmt.executeUpdate();
            clearInput();
            JOptionPane.showMessageDialog(null, "Data is successfully inserted!!");

        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void profileUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileUpdateBtnActionPerformed
        profileUpdate profileUpdt = new profileUpdate();
        profileUpdt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileUpdateBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PaymentForm payment = new PaymentForm();
        payment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void clearInput(){
        memberIdTxtfld.setText("");
        bookingIdTxtfld.setText("");
        numOfCourtTxtfld.setText("");
        activityTxtfld.setText("");
        scheduleTxtfld.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingInputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingInputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLbl;
    private javax.swing.JTextField activityTxtfld;
    private javax.swing.JLabel bookingIdLbl;
    private javax.swing.JTextField bookingIdTxtfld;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel inputBookingInformationLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel listActivityLbl1;
    private javax.swing.JLabel listActivityLbl2;
    private javax.swing.JLabel listScheduleLbl;
    private javax.swing.JLabel memberIdLbl;
    private javax.swing.JTextField memberIdTxtfld;
    private javax.swing.JLabel numOfCourtLbl;
    private javax.swing.JTextField numOfCourtTxtfld;
    private javax.swing.JButton profileUpdateBtn;
    private javax.swing.JLabel requestActivityLbl;
    private javax.swing.JLabel requestScheduleLbl;
    private javax.swing.JLabel scheduleLbl;
    private javax.swing.JTextField scheduleTxtfld;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
