package projectGUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHUN
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class BookingOutputForm extends javax.swing.JFrame {
    Connection myConn;
    Statement myStat;
    ResultSet myRs;
    PreparedStatement pstmt;
    /**
     * Creates new form BookingOutputForm
     */
    public BookingOutputForm() {
        initComponents();
        setConnect();
    }
    
    public void setConnect(){
        try{
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_oop", "root", "");         //databaseName
        //JOptionPane.showMessageDialog(null, "Connection success!!");
        
        myStat = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
        myRs = myStat.executeQuery("SELECT * from booking");                                        //tableName
        
        myRs.next();
        memberIdTxtfld.setText(myRs.getString("memberID"));
        bookingIdTxtfld.setText(myRs.getString("bookingID"));
        numOfCourtTxtfld.setText(String.valueOf(myRs.getInt("numOfCourt")));
        activityTxtfld.setText(myRs.getString("activity"));
        scheduleTxtfld.setText(myRs.getString("schedule"));
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backMainPageBtn = new javax.swing.JButton();
        bookingPanel = new javax.swing.JPanel();
        memberIdLbl = new javax.swing.JLabel();
        numOfCourtLbl = new javax.swing.JLabel();
        bookingIdLbl = new javax.swing.JLabel();
        memberIdTxtfld = new javax.swing.JTextField();
        bookingIdTxtfld = new javax.swing.JTextField();
        numOfCourtTxtfld = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        activityLbl = new javax.swing.JLabel();
        activityTxtfld = new javax.swing.JTextField();
        scheduleLbl = new javax.swing.JLabel();
        scheduleTxtfld = new javax.swing.JTextField();
        updateprofileBtn = new javax.swing.JButton();
        manageBookingInformationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backMainPageBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backMainPageBtn.setForeground(new java.awt.Color(204, 0, 204));
        backMainPageBtn.setText("BACK MAIN PAGE");
        backMainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMainPageBtnActionPerformed(evt);
            }
        });

        bookingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        memberIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        memberIdLbl.setText("Member ID:");

        numOfCourtLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numOfCourtLbl.setText("Num Of Court:");

        bookingIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookingIdLbl.setText("Booking ID:");

        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 0, 204));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(204, 0, 204));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        previousBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        previousBtn.setForeground(new java.awt.Color(255, 0, 204));
        previousBtn.setText("< PREVIOUS");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 0, 204));
        nextBtn.setText("> NEXT");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        activityLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        activityLbl.setText("Activity: ");

        scheduleLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleLbl.setText("Schedule:");

        updateprofileBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateprofileBtn.setForeground(new java.awt.Color(255, 0, 204));
        updateprofileBtn.setText("Update Profile");
        updateprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateprofileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(previousBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberIdLbl)
                    .addComponent(bookingIdLbl)
                    .addComponent(numOfCourtLbl)
                    .addComponent(activityLbl)
                    .addComponent(scheduleLbl))
                .addGap(51, 51, 51)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberIdTxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(bookingIdTxtfld)
                    .addComponent(numOfCourtTxtfld)
                    .addComponent(scheduleTxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(activityTxtfld))
                .addGap(37, 37, 37)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateprofileBtn)
                .addGap(249, 249, 249))
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdLbl)
                    .addComponent(memberIdTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIdLbl)
                    .addComponent(bookingIdTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn))
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfCourtLbl)
                    .addComponent(numOfCourtTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activityLbl)
                            .addComponent(scheduleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(deleteBtn)))
                .addGap(17, 17, 17)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleLbl))
                .addGap(18, 18, 18)
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousBtn)
                    .addComponent(nextBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(updateprofileBtn)
                .addContainerGap())
        );

        manageBookingInformationLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        manageBookingInformationLbl.setText("Manage Booking Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(manageBookingInformationLbl)
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(backMainPageBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(manageBookingInformationLbl)
                .addGap(40, 40, 40)
                .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(backMainPageBtn)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMainPageBtnActionPerformed
        // TODO add your handling code here:
        BookingInputForm firstForm = new BookingInputForm();                                //inputForm
        firstForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMainPageBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
       try{
            myRs.updateString(1, memberIdTxtfld.getText());
            myRs.updateString(2, bookingIdTxtfld.getText());
            myRs.updateInt(3, Integer.parseInt(numOfCourtTxtfld.getText()));
            myRs.updateString(5, activityTxtfld.getText());
            myRs.updateString(6, scheduleTxtfld.getText());
            myRs.updateRow();
            //cleanInput();
            JOptionPane.showMessageDialog(null, "Data is successfully updated!!");
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            myRs.deleteRow();
            myStat.close();
            myRs.close();
            JOptionPane.showMessageDialog(null, "Data is succesfully deleted!!");

            myStat = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            myRs = myStat.executeQuery("SELECT * from booking");              //tablename

            myRs.next();
            memberIdTxtfld.setText(myRs.getString("memberID"));
            bookingIdTxtfld.setText(myRs.getString("bookingID"));
            numOfCourtTxtfld.setText(String.valueOf(myRs.getInt("numOfCourt")));
            activityTxtfld.setText(myRs.getString("activity"));
            scheduleTxtfld.setText(myRs.getString("schedule"));
           
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TODO add your handling code here:
        try{
          if(myRs.previous()){
          memberIdTxtfld.setText(myRs.getString("memberID"));
          bookingIdTxtfld.setText(myRs.getString("bookingID"));
          numOfCourtTxtfld.setText(String.valueOf(myRs.getInt("numOfCourt")));
          activityTxtfld.setText(myRs.getString("activity"));
          scheduleTxtfld.setText(myRs.getString("schedule"));
          }else{
              myRs.next();
              JOptionPane.showMessageDialog(null, "Start of Data!!");
          }
            
            
        }catch(SQLException e){
             JOptionPane.showMessageDialog(BookingOutputForm.this,e.getMessage());             //outputForm
        }
    }//GEN-LAST:event_previousBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        try{
         if(myRs.next()){
          memberIdTxtfld.setText(myRs.getString("memberID"));
          bookingIdTxtfld.setText(myRs.getString("bookingID"));
          numOfCourtTxtfld.setText(String.valueOf(myRs.getInt("numOfCourt")));
          activityTxtfld.setText(myRs.getString("activity"));
          scheduleTxtfld.setText(myRs.getString("schedule"));
          
         }   else{
             myRs.previous();
             JOptionPane.showMessageDialog(null, "End of Data!!");
         }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(BookingOutputForm.this,e.getMessage());         //outputForm
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void updateprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateprofileBtnActionPerformed
        // TODO add your handling code here:
        profileUpdate update = new profileUpdate();
        update.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateprofileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingOutputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingOutputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingOutputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingOutputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingOutputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLbl;
    private javax.swing.JTextField activityTxtfld;
    private javax.swing.JButton backMainPageBtn;
    private javax.swing.JLabel bookingIdLbl;
    private javax.swing.JTextField bookingIdTxtfld;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel manageBookingInformationLbl;
    private javax.swing.JLabel memberIdLbl;
    private javax.swing.JTextField memberIdTxtfld;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel numOfCourtLbl;
    private javax.swing.JTextField numOfCourtTxtfld;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel scheduleLbl;
    private javax.swing.JTextField scheduleTxtfld;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateprofileBtn;
    // End of variables declaration//GEN-END:variables
}
