package projectGUI;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bryan
 */
public class PaymentForm extends javax.swing.JFrame {
    Connection myConn;
    Statement myStatmt;
    ResultSet myRs;
    PreparedStatement pStatmt;
    
    public PaymentForm() {
        initComponents();
        ewalletJPanel.setVisible(false);
        cardJPanel.setVisible(false);
        priceTxtFld.setEditable(false);
        receiptArea.setEditable(false);
        pack();
        setConnect();
    }
    public void setConnect(){
        try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_oop", "root", "");
            //JOptionPane.showMessageDialog(null, "Connection success!!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payMethodBtnGrp = new javax.swing.ButtonGroup();
        ewalletBtnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mbIDTxtFld = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cardRadioBtn = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        ewalletRadioBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        priceTxtFld = new javax.swing.JTextField();
        ewalletJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ewalletPayBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BOORadioBtn = new javax.swing.JRadioButton();
        TNGRadioBtn = new javax.swing.JRadioButton();
        BIGRadioBtn = new javax.swing.JRadioButton();
        ewalletIDTxtFld = new javax.swing.JTextField();
        ewalletReceiptBtn = new javax.swing.JButton();
        eResetBtn = new javax.swing.JButton();
        cardJPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cardNumTxtFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cardNameTxtFld = new javax.swing.JTextField();
        cardPayBtn = new javax.swing.JButton();
        cardReceiptBtn = new javax.swing.JButton();
        cResetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptArea = new javax.swing.JTextArea();
        returnBookingBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Member ID :");

        mbIDTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Method :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        payMethodBtnGrp.add(cardRadioBtn);
        cardRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardRadioBtn.setText("Debit/Credit Card");

        nextBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(0, 102, 204));
        nextBtn.setText("Next");
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        payMethodBtnGrp.add(ewalletRadioBtn);
        ewalletRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ewalletRadioBtn.setText("E-Wallet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ewalletRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(cardRadioBtn)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardRadioBtn)
                    .addComponent(ewalletRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Total Price :");

        priceTxtFld.setBackground(new java.awt.Color(255, 255, 204));
        priceTxtFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mbIDTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbIDTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ewalletJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter E-Wallet ID (Phone number) : ");

        ewalletPayBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ewalletPayBtn.setForeground(new java.awt.Color(255, 153, 0));
        ewalletPayBtn.setText("Pay Now");
        ewalletPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ewalletPayBtnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-wallet Type : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        ewalletBtnGrp.add(BOORadioBtn);
        BOORadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BOORadioBtn.setText("Boost");

        ewalletBtnGrp.add(TNGRadioBtn);
        TNGRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TNGRadioBtn.setText("Touch N Go");

        ewalletBtnGrp.add(BIGRadioBtn);
        BIGRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BIGRadioBtn.setText("BigPay");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TNGRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOORadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BIGRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNGRadioBtn)
                    .addComponent(BOORadioBtn)
                    .addComponent(BIGRadioBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ewalletIDTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ewalletReceiptBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ewalletReceiptBtn.setForeground(new java.awt.Color(51, 51, 51));
        ewalletReceiptBtn.setText("Generate Receipt");
        ewalletReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ewalletReceiptBtnActionPerformed(evt);
            }
        });

        eResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eResetBtn.setForeground(new java.awt.Color(255, 51, 51));
        eResetBtn.setText("Reset");
        eResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ewalletJPanelLayout = new javax.swing.GroupLayout(ewalletJPanel);
        ewalletJPanel.setLayout(ewalletJPanelLayout);
        ewalletJPanelLayout.setHorizontalGroup(
            ewalletJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ewalletJPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ewalletJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ewalletJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ewalletJPanelLayout.createSequentialGroup()
                        .addComponent(ewalletPayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ewalletReceiptBtn)
                        .addGap(31, 31, 31)
                        .addComponent(eResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(ewalletJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ewalletIDTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        ewalletJPanelLayout.setVerticalGroup(
            ewalletJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ewalletJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ewalletJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ewalletIDTxtFld))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(ewalletJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ewalletPayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(ewalletReceiptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter Debit/Credit Card number : ");

        cardNumTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Enter card holder name : ");

        cardNameTxtFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cardPayBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardPayBtn.setForeground(new java.awt.Color(255, 153, 0));
        cardPayBtn.setText("Pay Now");
        cardPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPayBtnActionPerformed(evt);
            }
        });

        cardReceiptBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardReceiptBtn.setForeground(new java.awt.Color(51, 51, 51));
        cardReceiptBtn.setText("Generate Receipt");
        cardReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardReceiptBtnActionPerformed(evt);
            }
        });

        cResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cResetBtn.setForeground(new java.awt.Color(255, 51, 51));
        cResetBtn.setText("Reset");
        cResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardJPanelLayout = new javax.swing.GroupLayout(cardJPanel);
        cardJPanel.setLayout(cardJPanelLayout);
        cardJPanelLayout.setHorizontalGroup(
            cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardNameTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(cardNumTxtFld)))
                    .addGroup(cardJPanelLayout.createSequentialGroup()
                        .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardPayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addComponent(cardReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        cardJPanelLayout.setVerticalGroup(
            cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardJPanelLayout.createSequentialGroup()
                        .addComponent(cardNumTxtFld)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardJPanelLayout.createSequentialGroup()
                        .addComponent(cardNameTxtFld)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(cardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardPayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        receiptArea.setColumns(20);
        receiptArea.setRows(5);
        jScrollPane1.setViewportView(receiptArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        returnBookingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnBookingBtn.setText("< Return to Booking");
        returnBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cardJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ewalletJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(returnBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(returnBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ewalletJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        try{
            String membertid = mbIDTxtFld.getText();
            myStatmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            myRs = myStatmt.executeQuery("SELECT * FROM booking WHERE memberID='"+membertid+"'");
            
            if(myRs.next()){
                String totalprice = String.valueOf(myRs.getDouble("price") * myRs.getInt("numOfCourt"));
                priceTxtFld.setText(totalprice);
                
                if(ewalletRadioBtn.isSelected()==true){
                ewalletJPanel.setVisible(true);
                cardJPanel.setVisible(false);
                pack();
                }else if(cardRadioBtn.isSelected()==true){
                    ewalletJPanel.setVisible(false);
                    cardJPanel.setVisible(true);
                    pack();
                }else{
                    JOptionPane.showMessageDialog(null, "Please select Payment Method!!");
                }
                ewalletReceiptBtn.setVisible(false);
                cardReceiptBtn.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Member ID!!");
                ewalletJPanel.setVisible(false);
                cardJPanel.setVisible(false);
                pack();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void ewalletPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ewalletPayBtnActionPerformed
        ewalletReceiptBtn.setVisible(false);
        String SQL = "INSERT INTO ewallet VALUES(?,?,?,?,?)";
        String wallet = null;
        String memberid = mbIDTxtFld.getText();
        try{
            pStatmt = myConn.prepareStatement(SQL);
            if(ewalletIDTxtFld.getText().isEmpty()){        //verify whether textfield is empty or not
                JOptionPane.showMessageDialog(null,"E-wallet ID cannot be empty!!");
            }else{
                pStatmt.setString(1, ewalletIDTxtFld.getText());
            }
            if(TNGRadioBtn.isSelected()==true){
                wallet="TNG";
            } else if(BOORadioBtn.isSelected()==true){
                wallet="Boost";
            } else if(BIGRadioBtn.isSelected()==true){
                wallet="BigPay";
            } else {
                JOptionPane.showMessageDialog(null, "Please select an E-wallet type!!");
            }
            pStatmt.setString(2, wallet);
            pStatmt.setString(3, memberid);
            pStatmt.setDouble(4, Double.valueOf(priceTxtFld.getText()));
            String paymentid = memberid.concat(ewalletIDTxtFld.getText());
            pStatmt.setString(5, paymentid);
            pStatmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Receiveing payment...\nPayment Received!!");
            ewalletReceiptBtn.setVisible(true);
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_ewalletPayBtnActionPerformed

    private void cardPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPayBtnActionPerformed
        cardReceiptBtn.setVisible(false);
        String SQL = "INSERT INTO creditDebitCard VALUES(?,?,?,?,?)";
        String memberid = mbIDTxtFld.getText();
        try{
            pStatmt = myConn.prepareStatement(SQL);
            if(cardNumTxtFld.getText().isEmpty()){        //verify whether textfield is empty or not
                JOptionPane.showMessageDialog(null,"Card No. cannot be empty!!");
            }else{
                pStatmt.setString(1, cardNumTxtFld.getText());
            }
            
            if(cardNameTxtFld.getText().isEmpty()){      //verify whether textfield is empty or not
                JOptionPane.showMessageDialog(null,"Card holder name cannot be empty!!");
            }else{
                pStatmt.setString(2, cardNameTxtFld.getText());
            }
            
            pStatmt.setString(3, memberid);
            pStatmt.setDouble(4, Double.valueOf(priceTxtFld.getText()));
            String paymentid = memberid.concat(cardNumTxtFld.getText());
            pStatmt.setString(5, paymentid);
            pStatmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Receiveing payment...\nPayment Received!!");
            cardReceiptBtn.setVisible(true);
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_cardPayBtnActionPerformed

    private void cResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cResetBtnActionPerformed
        mbIDTxtFld.setText("");
        payMethodBtnGrp.clearSelection();
        priceTxtFld.setText("");
        cardNumTxtFld.setText("");
        cardNameTxtFld.setText("");
        receiptArea.setText("");
    }//GEN-LAST:event_cResetBtnActionPerformed

    private void eResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eResetBtnActionPerformed
        mbIDTxtFld.setText("");
        payMethodBtnGrp.clearSelection();
        priceTxtFld.setText("");
        ewalletIDTxtFld.setText("");
        ewalletBtnGrp.clearSelection();
        receiptArea.setText("");
    }//GEN-LAST:event_eResetBtnActionPerformed

    private void ewalletReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ewalletReceiptBtnActionPerformed
        JOptionPane.showMessageDialog(null,"Generating receipt...");
        String SQL = "INSERT INTO receipt VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        try{
            myStatmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            myRs = myStatmt.executeQuery("SELECT b.memberID, b.bookingID, b.numOfCourt, b.price, b.activity, b.schedule, m.name, e.ewalletID, e.totalPrice, e.paymentID "
                    + "FROM booking b, membership m, ewallet e "
                    + "WHERE b.memberID=m.memberID AND b.memberID=e.memberID");
            String memberid = mbIDTxtFld.getText();
            
            while(myRs.next()){
                String compare = myRs.getString("memberID");
                if(memberid.equals(compare)){
                    String name = myRs.getString("m.name");
                    String receiptid = "UMP".concat(myRs.getString("e.ewalletID"));
                    String paymentid = myRs.getString("e.paymentID");
                    String addrs= "Universiti Malaysia Pahang, 26600 Pekan, Pahang";
                    pStatmt = myConn.prepareStatement(SQL);
                    pStatmt.setString(1, receiptid);
                    pStatmt.setString(2, paymentid);
                    pStatmt.setString(3, myRs.getString("b.memberID"));
                    pStatmt.setString(4, myRs.getString("m.name"));
                    pStatmt.setString(5, addrs);
                    pStatmt.setString(6, myRs.getString("b.bookingID"));
                    pStatmt.setInt(7, Integer.parseInt(myRs.getString("b.numOfCourt")));
                    pStatmt.setDouble(8, Double.valueOf(myRs.getString("b.price")));
                    pStatmt.setString(9, myRs.getString("b.activity"));
                    pStatmt.setString(10, myRs.getString("b.schedule"));
                    pStatmt.setDouble(11, Double.valueOf(myRs.getString("e.totalPrice")));
                    pStatmt.executeUpdate();
                    //begin of displaying receipt 
                    receiptArea.setText("\n\t\t     | E-Wallet Payment |");
                    receiptArea.setText(receiptArea.getText()+"\n================================ Receipt ================================");
                    receiptArea.setText(receiptArea.getText()+"\nReceipt ID : "+ receiptid);
                    receiptArea.setText(receiptArea.getText()+"\nName         : "+ myRs.getString("m.name"));
                    receiptArea.setText(receiptArea.getText()+"\nMember ID : "+ myRs.getString("b.memberID"));
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\nAddress    : "+addrs);
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\nBooking ID\tNumber of Court\tPrice\tActivity\tSchedule");
                    receiptArea.setText(receiptArea.getText()+"\n"+myRs.getString("b.bookingID")+"\t"+myRs.getString("b.numOfCourt")+"\t\t"+myRs.getString("b.price")+"\t"+myRs.getString("b.activity")+"\t"+myRs.getString("b.schedule"));
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\n\nTotal Price : RM"+ myRs.getString("e.totalPrice"));
                }else{
                    receiptArea.setText("\nError getting user data from database!!");
                    receiptArea.setText(receiptArea.getText()+"\nPlease check your Member ID!!");
                }
            }
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_ewalletReceiptBtnActionPerformed

    private void cardReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardReceiptBtnActionPerformed
        JOptionPane.showMessageDialog(null,"Generating receipt...");
        String SQL = "INSERT INTO receipt VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        try{
            myStatmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            myRs = myStatmt.executeQuery("SELECT b.memberID, b.bookingID, b.numOfCourt, b.price, b.activity, b.schedule, m.name, c.cardNo, c.totalPrice, c.paymentID "
                    + "FROM booking b, membership m, creditDebitCard c "
                    + "WHERE b.memberID=m.memberID AND b.memberID=c.memberID");
            String memberid = mbIDTxtFld.getText();
            
            while(myRs.next()){
                String compare = myRs.getString("memberID");
                if(memberid.equals(compare)){
                    String name = myRs.getString("m.name");
                    String receiptid = "UMP".concat(myRs.getString("c.cardNo"));
                    String paymentid = myRs.getString("c.paymentID");
                    String addrs= "Universiti Malaysia Pahang, 26600 Pekan, Pahang";
                    pStatmt = myConn.prepareStatement(SQL);
                    pStatmt.setString(1, receiptid);
                    pStatmt.setString(2, paymentid);
                    pStatmt.setString(3, myRs.getString("b.memberID"));
                    pStatmt.setString(4, myRs.getString("m.name"));
                    pStatmt.setString(5, addrs);
                    pStatmt.setString(6, myRs.getString("b.bookingID"));
                    pStatmt.setInt(7, Integer.parseInt(myRs.getString("b.numOfCourt")));
                    pStatmt.setDouble(8, Double.valueOf(myRs.getString("b.price")));
                    pStatmt.setString(9, myRs.getString("b.activity"));
                    pStatmt.setString(10, myRs.getString("b.schedule"));
                    pStatmt.setDouble(11, Double.valueOf(myRs.getString("c.totalPrice")));
                    pStatmt.executeUpdate();
                    //begin of displaying receipt 
                    receiptArea.setText("\n\t\t        | Card Payment |");
                    receiptArea.setText(receiptArea.getText()+"\n================================ Receipt ================================");
                    receiptArea.setText(receiptArea.getText()+"\nReceipt ID : "+ receiptid);
                    receiptArea.setText(receiptArea.getText()+"\nName         : "+ myRs.getString("m.name"));
                    receiptArea.setText(receiptArea.getText()+"\nMember ID : "+ myRs.getString("b.memberID"));
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\nAddress    : "+addrs);
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\nBooking ID\tNumber of Court\tPrice\tActivity\tSchedule");
                    receiptArea.setText(receiptArea.getText()+"\n"+myRs.getString("b.bookingID")+"\t"+myRs.getString("b.numOfCourt")+"\t\t"+myRs.getString("b.price")+"\t"+myRs.getString("b.activity")+"\t"+myRs.getString("b.schedule"));
                    receiptArea.setText(receiptArea.getText()+"\n========================================================================");
                    receiptArea.setText(receiptArea.getText()+"\n\nTotal Price : RM"+ myRs.getString("c.totalPrice"));
                }else{
                    receiptArea.setText("\nError getting user data from database!!");
                    receiptArea.setText(receiptArea.getText()+"\nPlease check your Member ID!!");
                }
            }
        }catch(Exception err){
            err.printStackTrace();
        }
    }//GEN-LAST:event_cardReceiptBtnActionPerformed

    private void returnBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookingBtnActionPerformed
        BookingInputForm booking = new BookingInputForm();
        booking.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBookingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BIGRadioBtn;
    private javax.swing.JRadioButton BOORadioBtn;
    private javax.swing.JRadioButton TNGRadioBtn;
    private javax.swing.JButton cResetBtn;
    private javax.swing.JPanel cardJPanel;
    private javax.swing.JTextField cardNameTxtFld;
    private javax.swing.JTextField cardNumTxtFld;
    private javax.swing.JButton cardPayBtn;
    private javax.swing.JRadioButton cardRadioBtn;
    private javax.swing.JButton cardReceiptBtn;
    private javax.swing.JButton eResetBtn;
    private javax.swing.ButtonGroup ewalletBtnGrp;
    private javax.swing.JTextField ewalletIDTxtFld;
    private javax.swing.JPanel ewalletJPanel;
    private javax.swing.JButton ewalletPayBtn;
    private javax.swing.JRadioButton ewalletRadioBtn;
    private javax.swing.JButton ewalletReceiptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mbIDTxtFld;
    private javax.swing.JButton nextBtn;
    private javax.swing.ButtonGroup payMethodBtnGrp;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JTextArea receiptArea;
    private javax.swing.JButton returnBookingBtn;
    // End of variables declaration//GEN-END:variables
}
